force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant_Lease_Association__c/Tenant_Lease_Association__c.object-meta.xml
<CustomObject>
    <description>To associate leases with tenants</description>
    <label>Tenant Lease Association</label>
    <nameField>
        <displayFormat>TLA-{0000}</displayFormat>
        <label>Tenant Lease Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tenant Lease Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant_Lease_Association__c/fields/Is_Primary_Tenant__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary_Tenant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Tenant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tenant_Lease_Association__c/fields/Lease__c.field-meta.xml
<CustomField>
    <fullName>Lease__c</fullName>
    <label>Lease</label>
    <referenceTo>Lease__c</referenceTo>
    <relationshipLabel>Tenant Lease Associations</relationshipLabel>
    <relationshipName>Tenant_Lease_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TenantLeaseAssociationService.cls
/**
 * Description: To handle Tenant_Lease_Association__c busienss logic
 * @author Victor Espiritu 
 */
public with sharing class TenantLeaseAssociationService {
    
    
    /**
     * Description: prevents a lease from having no primary tenant as a primary tenant per lease is required
     * @param newRecords the new records being triggered
     * @param oldRecords the previous versions of the records being triggered
     */
    public static void preventALeaseWithNoPrimaryTenant(List<Tenant_Lease_Association__c> newRecords, List<Tenant_Lease_Association__c> oldRecords) {

        Set<Id> leaseIds = new Set<Id>();

        for (Tenant_Lease_Association__c tla : newRecords) {
            if (tla.Lease__c != null) {
                leaseIds.add(tla.Lease__c);
            }
        }

        if (leaseIds.isEmpty()) {
            return;
        }

        Map<Id, Integer> primaryCountByLeaseId = new Map<Id, Integer>();

        for (Id leaseId : leaseIds) {
            primaryCountByLeaseId.put(leaseId, 0);
        }

        List<Tenant_Lease_Association__c> existingTlas = TenantLeaseAssociationSelector.getTenantLeaseAssocByLeaseId(new List<Id>(leaseIds));

        for (Tenant_Lease_Association__c tla : existingTlas) {

            if (tla.Is_Primary_Tenant__c) {
                primaryCountByLeaseId.put(tla.Lease__c, primaryCountByLeaseId.get(tla.Lease__c) + 1);
            }
        }

        if (oldRecords == null) {

            for (Tenant_Lease_Association__c tla : newRecords) {

                if (tla.Lease__c != null && tla.Is_Primary_Tenant__c) {
                    primaryCountByLeaseId.put(tla.Lease__c, primaryCountByLeaseId.get(tla.Lease__c) + 1);
                }

            }
        } else {

            Map<Id, Tenant_Lease_Association__c> oldRecordsById = new Map<Id, Tenant_Lease_Association__c>(oldRecords);

            for (Tenant_Lease_Association__c newTla : newRecords) {

                Tenant_Lease_Association__c oldTla = oldRecordsById.get(newTla.Id);

                if (oldTla == null) {
                    continue;
                }

                if (oldTla.Is_Primary_Tenant__c && !newTla.Is_Primary_Tenant__c) {

                    primaryCountByLeaseId.put(newTla.Lease__c, primaryCountByLeaseId.get(newTla.Lease__c) - 1);

                } else if (!oldTla.Is_Primary_Tenant__c && newTla.Is_Primary_Tenant__c) {

                    primaryCountByLeaseId.put(
                        newTla.Lease__c,
                        primaryCountByLeaseId.get(newTla.Lease__c) + 1
                    );

                }
            }
        }

        // Validate final state
        for (Tenant_Lease_Association__c tla : newRecords) {

            if (tla.Lease__c != null && primaryCountByLeaseId.get(tla.Lease__c) == 0) {
                tla.addError('A lease must have a primary tenant.');
            }
            
        }
    }
    
    /**
     * Description: synchronize the primary tenant in the tenant lease association as only one primary 
     * tenant should be present
     * @param newRecords the new records being changed
     */
    public static void synchronizePrimaryTenant(List<Tenant_Lease_Association__c> newRecords){

        

    }

}