force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Leases</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>P#-{0000000}</displayFormat>
        <label>Property Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property_Owner__c.field-meta.xml
<CustomField>
    <fullName>Property_Owner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Status__c.field-meta.xml
<CustomField>
    <fullName>Property_Status__c</fullName>
    <label>Property Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Under Renovation</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>US_States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tenant__c/Tenant__c.object-meta.xml
<CustomObject>
    <label>Tenant</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testUtils.cls
/**
 * Description: TestUtils for Property Management app
 * @author Victor Espiritu 
 */
@IsTest
public class testUtils {

    public static List<Account> CreateAccounts(Integer accountsToCreate, String recordType){

        List<Account> accts = new List<Account>();
        Id accountPropertyOwnerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
                                                            .get(recordType).getRecordTypeId();

        for (Integer i = 0; i < accountsToCreate; i++) {
            accts.add(new Account(RecordTypeId = accountPropertyOwnerRecordTypeId,
                                    Name = 'Test Account ' + i));
        }

        return accts;

    }

    public static List<Property__c> CreateProperties(Integer propertiesToCreate, Account propertyOwner){

        List<Property__c> properties = new List<Property__c>();

        for (Integer i = 0; i < propertiesToCreate; i++) {
            properties.add(new Property__c(Property_Owner__c = propertyOwner.Id,
                                                Property_Status__c = 'Active',
                                                Street_Address__c = '123 Test St',
                                                City__c = 'Test',
                                                State__c = 'AL'));
        }

        return properties;

    }

    public static List<Lease__c> CreateLeases(Integer leasesToCreate, Property__c property){
        List<Lease__c> leases = new List<Lease__c>();

        for (Integer i = 0; i < leasesToCreate; i++) {
            leases.add(new Lease__c(Property__c = property.Id));
        }

        return leases;
    }

    public static List<Tenant__c> CreateTenants(Integer tenantsToCreate){
        List<Tenant__c> tenants = new List<Tenant__c>();

        for (Integer i = 0; i < tenantsToCreate; i++) {
            tenants.add(new Tenant__c(Last_Name__c = 'Test Tenant ' + i));
        }

        return tenants;
    }

}