force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant__c/Tenant__c.object-meta.xml
<CustomObject>
    <label>Tenant</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant_Lease_Association__c/Tenant_Lease_Association__c.object-meta.xml
<CustomObject>
    <description>To associate leases with tenants</description>
    <label>Tenant Lease Association</label>
    <nameField>
        <displayFormat>TLA-{0000}</displayFormat>
        <label>Tenant Lease Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tenant Lease Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant_Lease_Association__c/fields/Is_Primary_Tenant__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary_Tenant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Tenant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tenant_Lease_Association__c/fields/Lease__c.field-meta.xml
<CustomField>
    <fullName>Lease__c</fullName>
    <label>Lease</label>
    <referenceTo>Lease__c</referenceTo>
    <relationshipLabel>Tenant Lease Associations</relationshipLabel>
    <relationshipName>Tenant_Lease_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tenant_Lease_Association__c/fields/Occupant_Type__c.field-meta.xml
<CustomField>
    <fullName>Occupant_Type__c</fullName>
    <label>Occupant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tenant</fullName>
            </value>
            <value>
                <fullName>Co-Tenant</fullName>
            </value>
            <value>
                <fullName>Occupant</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tenant_Lease_Association__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Tenant__c</referenceTo>
    <relationshipLabel>Tenant Lease Associations</relationshipLabel>
    <relationshipName>Tenant_Lease_Associations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TenantLeaseAssociationSelector.cls
/**
 * Description: To handle Tenant_Lease_Association__c queries
 * @author Victor Espiritu 
 */
public with sharing class TenantLeaseAssociationSelector {


    /**
     * Description: gets all the Tenant Lease Associations of the passed in leaseIds
     * @param leaseIds the passed in lease ids to get all the tenant lease associations of it
     */
    public static List<Tenant_Lease_Association__c> getTenantLeaseAssocByLeaseId(List<Id> leaseIds){

        return [
                SELECT
                    Id,
                    Lease__c,
                    Tenant__c,
                    Is_Primary_Tenant__c,
                    Occupant_Type__c
                FROM
                    Tenant_Lease_Association__c
                WHERE
                    Lease__c IN : leaseIds
            ];

    }

}